### ISSUE TITLE
APP 书架界面出现书籍消失又出现的动画

### ISSUE THREAD

**Issue by Mercy1101** [aruis/BookTime#3]
作者你好，我在手机端下载了你的APP并添加了两本书，然后出现以下画面，想问下这是正常的现象么

![Untitled1](https://github.com/aruis/BookTime/assets/25027160/54316e13-7e4f-4917-86af-a8c11d5a830b)

我的手机为 IPhone12 系统为 IOS 17.2

出现该动画的过程中手机为竖直方向且全程无晃动。

**Comment by aruis** [comment]
确实不对劲，之前没遇到过，我看我这边能重现不。

**Comment by aruis** [comment]
用仿真器测试了下，没有重现呢，不知道你那边杀了进程之后能稳定重现么？

**Comment by Mercy1101** [comment]
> 用仿真器测试了下，没有重现呢，不知道你那边杀了进程之后能稳定重现么？

我是在第一次安装且添加书籍后出现，后续打开没有再出现过这种情况，都是正常显示。

**Comment by Mercy1101** [comment]
该问题没有再重现，不影响正常使用，暂时关闭该问题
